use super::object::BodyHandle;

/// Event generated by the physics engine.  
/// In case of an overlap between a solid body and sensor the solid body is guaranteed to be the first handle.
#[derive(Debug, Clone, Copy)]
pub enum PhysicsEvent {
    // TODO: Should it include the normal for 2 solid bodies or not?
    // TODO: Include user supplied type
    OverlapStarted(BodyHandle, BodyHandle),
    OverlapEnded(BodyHandle, BodyHandle),
    CollisionStarted(BodyHandle, BodyHandle),
    CollisionEnded(BodyHandle, BodyHandle),
}
